### ISSUE TITLE
list versions doesn't show all versions

### ISSUE THREAD

**Issue by itaysk** [timgluz/asdf-bats#1]
```
❯ asdf list all bats
v0.1.0
```

**Comment by timgluz** [comment]
@itaysk Thanks for your report; Do you mind to share more details about your shell & Distro? 
I will try to replicate it on similar environment and add missing test-vector for Github action

**Comment by itaysk** [comment]
Sure, let me know if any other info will help
```
❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan

❯ zsh --version
zsh 5.7.1 (x86_64-ubuntu-linux-gnu)
```
